import { useState } from "react";
import { useNavigate } from "react-router-dom";

export default function RegisterPatient() {
  const navigate = useNavigate();

  const [form, setForm] = useState({
    name: "",
    email: "",
    phone: "",
    age: "",
    gender: "",
    bloodGroup: "",
    address: "",
    emergencyContact: "",
    emergencyContactName: "",
  });

  const [errors, setErrors] = useState({});
  const [loading, setLoading] = useState(false);

  const handleChange = (e) => {
    const { name, value } = e.target;

    setForm((prev) => ({
      ...prev,
      [name]: value,
    }));

    setErrors((prev) => ({
      ...prev,
      [name]: "",
      submit: "",
    }));
  };

  const validate = () => {
    const newErrors = {};

    if (!form.name.trim()) {
      newErrors.name = "Name is required";
    }

    if (!form.email.trim()) {
      newErrors.email = "Email is required";
    } else if (
      !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(form.email.trim())
    ) {
      newErrors.email = "Enter a valid email";
    }

    if (!form.phone.trim()) {
      newErrors.phone = "Phone number is required";
    } else if (
      !/^[0-9+\-\s]{10,15}$/.test(form.phone.trim())
    ) {
      newErrors.phone = "Enter a valid phone number";
    }

    if (!form.age) {
      newErrors.age = "Age is required";
    } else if (
      Number(form.age) < 0 ||
      Number(form.age) > 130
    ) {
      newErrors.age = "Enter a valid age";
    }

    if (!form.gender) {
      newErrors.gender = "Please select gender";
    }

    if (!form.bloodGroup) {
      newErrors.bloodGroup = "Please select blood group";
    }

    if (!form.address.trim()) {
      newErrors.address = "Address is required";
    }

    if (!form.emergencyContactName.trim()) {
      newErrors.emergencyContactName =
        "Emergency contact name is required";
    }

    if (!form.emergencyContact.trim()) {
      newErrors.emergencyContact =
        "Emergency contact number is required";
    } else if (
      !/^[0-9+\-\s]{10,15}$/.test(
        form.emergencyContact.trim()
      )
    ) {
      newErrors.emergencyContact =
        "Enter a valid contact number";
    }

    setErrors(newErrors);

    return Object.keys(newErrors).length === 0;
  };

  const handleSubmit = async (e) => {
    e.preventDefault();

    if (!validate()) {
      return;
    }

    setLoading(true);

    try {
      const response = await fetch(
        "https://emmc-push-backend.onrender.com/api/patients/register",
        {
          method: "POST",

          headers: {
            "Content-Type": "application/json",
          },

          body: JSON.stringify({
            name: form.name.trim(),

            email: form.email
              .trim()
              .toLowerCase(),

            phone: form.phone.trim(),

            age: Number(form.age),

            gender: form.gender,

            bloodGroup: form.bloodGroup,

            address: form.address.trim(),
            fullAddress: form.address.trim(),

            emergencyContact:
              form.emergencyContact.trim(),

            emergencyContactName:
              form.emergencyContactName.trim(),
            emPhone: form.emergencyContact.trim(),
            emName: form.emergencyContactName.trim(),
          }),
        }
      );

      const responseText =
        await response.text();

      let data = {};

      try {
        data = responseText
          ? JSON.parse(responseText)
          : {};
      } catch (error) {
        console.error(
          "Invalid backend response:",
          responseText
        );
      }

      if (!response.ok) {
        setLoading(false);

        setErrors({
          submit:
            data.message ||
            data.error ||
            `Patient registration failed (HTTP ${response.status}).`,
        });

        return;
      }

      /*
       * Get Patient ID generated by backend.
       */

      const actualPatientId =
        data?.patient?.patientId ||
        data?.patientId ||
        data?.data?.patientId ||
        "";

      /*
       * If backend did not return Patient ID,
       * don't move to password page.
       */

      if (!actualPatientId) {
        setLoading(false);

        setErrors({
          submit:
            "Registration completed, but Patient ID was not received from backend.",
        });

        return;
      }

      /*
       * Save Patient ID.
       *
       * CreatePatientPassword.jsx will automatically
       * read this ID.
       */

      localStorage.setItem(
        "pendingPatientId",
        actualPatientId
      );

      /*
       * Save basic patient information.
       */

      localStorage.setItem(
        "pendingPatientData",
        JSON.stringify({
          patientId: actualPatientId,

          name: form.name.trim(),

          email: form.email
            .trim()
            .toLowerCase(),
        })
      );

      setLoading(false);

      /*
       * IMPORTANT:
       *
       * Directly open Create Password page.
       *
       * NO redirect to "/"
       */

      navigate("/create-password", {
        replace: true,
      });
    } catch (error) {
      console.error(
        "PATIENT REGISTRATION ERROR:",
        error
      );

      setLoading(false);

      setErrors({
        submit:
          error?.message ||
          "Cannot connect to the EMMC Render backend.",
      });
    }
  };

  return (
    <div className="registration-page">

      <div className="background-overlay" />

      {/* ================= HEADER ================= */}

      <header className="registration-header">

        <div className="brand">

          <img
            src="/logo.png"
            alt="EMMC Logo"
            className="brand-logo-image"
          />

        </div>

        <div className="header-right">

          <div className="secure-badge">
            🔒 Secure Registration
          </div>

          <button
            type="button"
            className="back-button"
            onClick={() => navigate("/signin")}
          >
            ← Back to Sign In
          </button>

        </div>

      </header>

      {/* ================= MAIN ================= */}

      <main className="registration-container">

        <div className="page-heading">

          <div className="heading-content">

            <span className="eyebrow">
              PATIENT ONBOARDING
            </span>

            <h1>
              Complete Your Patient Profile
            </h1>

            <p>
              Please provide your details so EMMC
              can deliver faster and safer emergency
              care.
            </p>

            <div className="heading-line" />

          </div>

          <div className="step-indicator">

            <div className="step active">
              <span>1</span>
              Personal
            </div>

            <div className="step-line" />

            <div className="step">
              <span>2</span>
              Emergency
            </div>

          </div>

        </div>

        {/* ================= FORM ================= */}

        <form
          className="registration-form"
          onSubmit={handleSubmit}
        >

          {/* ================= PERSONAL ================= */}

          <section className="form-section">

            <div className="section-heading">

              <div className="section-number">
                01
              </div>

              <div>
                <h2>
                  Personal Information
                </h2>

                <p>
                  Basic information about the patient
                </p>
              </div>

            </div>

            <div className="form-grid">

              <div className="field field-full">

                <label>
                  Full Name <span>*</span>
                </label>

                <input
                  type="text"
                  name="name"
                  value={form.name}
                  onChange={handleChange}
                  placeholder="Enter patient's full name"
                />

                {errors.name && (
                  <small className="error-text">
                    {errors.name}
                  </small>
                )}

              </div>

              <div className="field">

                <label>
                  Email Address <span>*</span>
                </label>

                <input
                  type="email"
                  name="email"
                  value={form.email}
                  onChange={handleChange}
                  placeholder="patient@email.com"
                />

                {errors.email && (
                  <small className="error-text">
                    {errors.email}
                  </small>
                )}

              </div>

              <div className="field">

                <label>
                  Phone Number <span>*</span>
                </label>

                <input
                  type="tel"
                  name="phone"
                  value={form.phone}
                  onChange={handleChange}
                  placeholder="+91 XXXXX XXXXX"
                />

                {errors.phone && (
                  <small className="error-text">
                    {errors.phone}
                  </small>
                )}

              </div>

              <div className="field">

                <label>
                  Age <span>*</span>
                </label>

                <input
                  type="number"
                  name="age"
                  min="0"
                  max="130"
                  value={form.age}
                  onChange={handleChange}
                  placeholder="Enter age"
                />

                {errors.age && (
                  <small className="error-text">
                    {errors.age}
                  </small>
                )}

              </div>

              <div className="field">

                <label>
                  Gender <span>*</span>
                </label>

                <select
                  name="gender"
                  value={form.gender}
                  onChange={handleChange}
                >

                  <option value="">
                    Select gender
                  </option>

                  <option value="Male">
                    Male
                  </option>

                  <option value="Female">
                    Female
                  </option>

                  <option value="Other">
                    Other
                  </option>

                </select>

                {errors.gender && (
                  <small className="error-text">
                    {errors.gender}
                  </small>
                )}

              </div>

              <div className="field">

                <label>
                  Blood Group <span>*</span>
                </label>

                <select
                  name="bloodGroup"
                  value={form.bloodGroup}
                  onChange={handleChange}
                >

                  <option value="">
                    Select blood group
                  </option>

                  <option value="A+">A+</option>
                  <option value="A-">A-</option>
                  <option value="B+">B+</option>
                  <option value="B-">B-</option>
                  <option value="AB+">AB+</option>
                  <option value="AB-">AB-</option>
                  <option value="O+">O+</option>
                  <option value="O-">O-</option>

                </select>

                {errors.bloodGroup && (
                  <small className="error-text">
                    {errors.bloodGroup}
                  </small>
                )}

              </div>

              <div className="field field-full">

                <label>
                  Full Address <span>*</span>
                </label>

                <textarea
                  name="address"
                  value={form.address}
                  onChange={handleChange}
                  placeholder="Enter your complete residential address"
                  rows="3"
                />

                {errors.address && (
                  <small className="error-text">
                    {errors.address}
                  </small>
                )}

              </div>

            </div>

          </section>

          {/* ================= EMERGENCY ================= */}

          <section className="form-section emergency-section">

            <div className="section-heading">

              <div className="section-number emergency-number">
                02
              </div>

              <div>

                <h2>
                  Emergency Contact
                </h2>

                <p>
                  Someone we can contact during an
                  emergency
                </p>

              </div>

            </div>

            <div className="form-grid">

              <div className="field">

                <label>
                  Contact Name <span>*</span>
                </label>

                <input
                  type="text"
                  name="emergencyContactName"
                  value={
                    form.emergencyContactName
                  }
                  onChange={handleChange}
                  placeholder="Emergency contact name"
                />

                {errors.emergencyContactName && (
                  <small className="error-text">
                    {
                      errors.emergencyContactName
                    }
                  </small>
                )}

              </div>

              <div className="field">

                <label>
                  Contact Number <span>*</span>
                </label>

                <input
                  type="tel"
                  name="emergencyContact"
                  value={
                    form.emergencyContact
                  }
                  onChange={handleChange}
                  placeholder="+91 XXXXX XXXXX"
                />

                {errors.emergencyContact && (
                  <small className="error-text">
                    {errors.emergencyContact}
                  </small>
                )}

              </div>

            </div>

          </section>

          {/* ================= ERROR ================= */}

          {errors.submit && (

            <div className="submit-error">

              <span>!</span>

              <div>
                {errors.submit}
              </div>

            </div>

          )}

          {/* ================= FOOTER ================= */}

          <div className="form-footer">

            <div className="privacy-note">

              <div className="privacy-icon">
                🛡️
              </div>

              <div>

                <strong>
                  Your information is secure
                </strong>

                <p>
                  Your information is securely stored
                  and used only for emergency
                  healthcare services.
                </p>

              </div>

            </div>

            <button
              type="submit"
              className="submit-button"
              disabled={loading}
            >

              {loading ? (
                <>
                  <span className="spinner" />
                  Registering...
                </>
              ) : (
                <>
                  Complete Registration
                  <span className="submit-arrow">
                    →
                  </span>
                </>
              )}

            </button>

          </div>

        </form>

        <footer className="page-footer">

          <strong>
            EMMC — Emergency Mobility Management &
            Coordination System
          </strong>

          <span>
            People | Technology | Faster Response |
            Safer Lives
          </span>

        </footer>

      </main>

      {/* ================= CSS ================= */}

      <style>{`

        * {
          box-sizing: border-box;
        }

        html,
        body,
        #root {
          margin: 0;
          min-height: 100%;
        }

        body {
          margin: 0;
        }

        .registration-page {
          min-height: 100vh;
          position: relative;
          overflow-x: hidden;

          background:
            linear-gradient(
              rgba(227, 242, 255, 0.78),
              rgba(244, 249, 255, 0.88)
            ),
            url("/background.jpeg")
              center / cover no-repeat;

          background-attachment: fixed;

          font-family:
            Inter,
            -apple-system,
            BlinkMacSystemFont,
            "Segoe UI",
            Arial,
            sans-serif;

          color: #172033;

          padding-bottom: 45px;
        }

        .background-overlay {
          position: fixed;
          inset: 0;
          z-index: 0;
          pointer-events: none;

          background:
            linear-gradient(
              90deg,
              rgba(231, 245, 255, 0.66),
              rgba(248, 252, 255, 0.48),
              rgba(229, 244, 255, 0.66)
            );

          backdrop-filter: blur(1px);
        }

        .registration-header {
          position: relative;
          z-index: 5;

          height: 76px;

          display: flex;
          align-items: center;
          justify-content: space-between;

          padding: 0 6%;

          background:
            rgba(255, 255, 255, 0.95);

          border-bottom:
            1px solid #dce5ef;

          box-shadow:
            0 4px 20px
            rgba(22, 55, 90, 0.07);

          backdrop-filter: blur(14px);
        }

        .brand {
          display: flex;
          align-items: center;
        }

        .brand-logo-image {
          width: 150px;
          height: 55px;

          object-fit: contain;

          display: block;

          filter:
            drop-shadow(
              0 2px 4px
              rgba(24, 63, 103, 0.15)
            );
        }

        .header-right {
          display: flex;
          align-items: center;
          gap: 14px;
        }

        .secure-badge {
          display: flex;
          align-items: center;
          gap: 7px;

          padding: 8px 14px;

          border-radius: 20px;

          background: #f0f7ff;

          border:
            1px solid #d6e8fb;

          color: #1769c2;

          font-size: 12px;
          font-weight: 700;
        }

        .back-button {
          padding: 9px 16px;

          border-radius: 20px;

          background: #fff;

          border:
            1px solid #c7d9ed;

          color: #1769c2;

          font-size: 12px;
          font-weight: 700;

          cursor: pointer;
        }

        .back-button:hover {
          background: #eef7ff;
        }

        .registration-container {
          position: relative;
          z-index: 2;

          width: min(1050px, 92%);

          margin: 38px auto 0;
        }

        .page-heading {
          display: flex;
          justify-content: space-between;
          align-items: flex-end;

          gap: 30px;

          margin-bottom: 27px;
        }

        .heading-content {
          flex: 1;
        }

        .eyebrow {
          display: inline-block;

          color: #176ed1;

          font-size: 12px;
          font-weight: 800;

          letter-spacing: 2px;
        }

        .page-heading h1 {
          margin: 8px 0;

          color: #15213a;

          font-size:
            clamp(30px, 4vw, 43px);

          line-height: 1.12;

          letter-spacing: -1.2px;

          font-weight: 800;
        }

        .page-heading p {
          margin: 0;

          max-width: 700px;

          color: #617087;

          font-size: 15px;

          line-height: 1.6;
        }

        .heading-line {
          width: 68px;
          height: 3px;

          margin-top: 15px;

          border-radius: 5px;

          background: #277be8;
        }

        .step-indicator {
          display: flex;
          align-items: center;
          gap: 10px;

          white-space: nowrap;

          padding-bottom: 3px;
        }

        .step {
          display: flex;
          align-items: center;
          gap: 7px;

          color: #8b96a7;

          font-size: 12px;
          font-weight: 700;
        }

        .step span {
          width: 30px;
          height: 30px;

          border-radius: 50%;

          display: flex;
          align-items: center;
          justify-content: center;

          background:
            rgba(232, 237, 244, 0.9);

          color: #7e8999;

          font-weight: 800;
        }

        .step.active {
          color: #176ed1;
        }

        .step.active span {
          background: #2178e8;

          color: #fff;

          box-shadow:
            0 5px 13px
            rgba(33, 120, 232, 0.23);
        }

        .step-line {
          width: 38px;
          height: 2px;

          background: #d6dee9;
        }

        .registration-form {
          background:
            rgba(255, 255, 255, 0.96);

          border:
            1px solid
            rgba(219, 228, 239, 0.95);

          border-radius: 22px;

          overflow: hidden;

          box-shadow:
            0 24px 65px
            rgba(24, 53, 87, 0.14);
        }

        .form-section {
          padding: 29px 34px;

          border-bottom:
            1px solid #e9eef4;
        }

        .emergency-section {
          background:
            linear-gradient(
              180deg,
              rgba(255, 250, 250, 0.88),
              rgba(255, 255, 255, 0.96)
            );
        }

        .section-heading {
          display: flex;
          align-items: center;

          gap: 13px;

          margin-bottom: 24px;
        }

        .section-number {
          width: 43px;
          height: 43px;

          flex-shrink: 0;

          display: flex;
          align-items: center;
          justify-content: center;

          border-radius: 13px;

          background: #edf5ff;

          color: #176ed1;

          font-size: 14px;
          font-weight: 800;

          border:
            1px solid #dcecff;
        }

        .emergency-number {
          background: #fff1f1;

          color: #c34242;

          border-color: #ffe0e0;
        }

        .section-heading h2 {
          margin: 0;

          color: #19253d;

          font-size: 17px;

          font-weight: 800;
        }

        .section-heading p {
          margin: 4px 0 0;

          color: #8490a1;

          font-size: 12px;
        }

        .form-grid {
          display: grid;

          grid-template-columns:
            repeat(2, minmax(0, 1fr));

          gap: 20px;
        }

        .field {
          display: flex;
          flex-direction: column;
        }

        .field-full {
          grid-column: 1 / -1;
        }

        .field label {
          margin-bottom: 8px;

          color: #465267;

          font-size: 12px;

          font-weight: 750;
        }

        .field label span {
          color: #df4646;
        }

        .field input,
        .field select,
        .field textarea {
          width: 100%;

          border:
            1px solid #d9e1eb;

          background: #fbfdff;

          border-radius: 10px;

          padding: 12px 14px;

          color: #1e293b;

          font-family: inherit;

          font-size: 13px;

          outline: none;

          transition:
            border-color 0.2s ease,
            box-shadow 0.2s ease,
            background 0.2s ease;
        }

        .field input,
        .field select {
          height: 45px;
        }

        .field textarea {
          min-height: 82px;

          resize: vertical;
        }

        .field input:focus,
        .field select:focus,
        .field textarea:focus {
          border-color: #4b93ed;

          background: #fff;

          box-shadow:
            0 0 0 3px
            rgba(75, 147, 237, 0.11);
        }

        .field input::placeholder,
        .field textarea::placeholder {
          color: #a1aab8;
        }

        .error-text {
          margin-top: 5px;

          color: #d94343;

          font-size: 11px;

          font-weight: 600;
        }

        .submit-error {
          display: flex;
          align-items: center;

          gap: 10px;

          margin: 18px 34px 0;

          padding: 12px 14px;

          border-radius: 10px;

          background: #fff2f2;

          border:
            1px solid #ffd8d8;

          color: #c33c3c;

          font-size: 12px;

          font-weight: 600;
        }

        .submit-error span {
          width: 21px;
          height: 21px;

          flex-shrink: 0;

          display: flex;
          align-items: center;
          justify-content: center;

          border-radius: 50%;

          background: #e15a5a;

          color: #fff;

          font-weight: 800;
        }

        .form-footer {
          display: flex;

          align-items: center;

          justify-content: space-between;

          gap: 25px;

          padding: 22px 34px;

          background: #f9fbfd;
        }

        .privacy-note {
          display: flex;

          align-items: center;

          gap: 11px;

          max-width: 510px;
        }

        .privacy-icon {
          width: 38px;
          height: 38px;

          flex-shrink: 0;

          display: flex;

          align-items: center;
          justify-content: center;

          border-radius: 10px;

          background: #edf6ff;

          font-size: 17px;
        }

        .privacy-note strong {
          display: block;

          margin-bottom: 2px;

          color: #334155;

          font-size: 12px;

          font-weight: 800;
        }

        .privacy-note p {
          margin: 0;

          color: #7a8697;

          font-size: 11px;

          line-height: 1.45;
        }

        .submit-button {
          min-width: 235px;

          height: 48px;

          border: none;

          border-radius: 10px;

          background:
            linear-gradient(
              135deg,
              #176fe4,
              #348cff
            );

          color: #fff;

          font-size: 13px;

          font-weight: 750;

          cursor: pointer;

          display: flex;

          align-items: center;

          justify-content: center;

          gap: 12px;

          box-shadow:
            0 9px 22px
            rgba(23, 111, 228, 0.22);
        }

        .submit-button:hover:not(:disabled) {
          transform:
            translateY(-1px);

          box-shadow:
            0 12px 28px
            rgba(23, 111, 228, 0.3);
        }

        .submit-button:disabled {
          opacity: 0.65;

          cursor: not-allowed;
        }

        .submit-arrow {
          font-size: 18px;
        }

        .spinner {
          width: 17px;
          height: 17px;

          border:
            2px solid
            rgba(255,255,255,0.4);

          border-top-color: white;

          border-radius: 50%;

          animation:
            registration-spin
            0.7s linear infinite;
        }

        @keyframes registration-spin {

          to {
            transform: rotate(360deg);
          }

        }

        .page-footer {
          display: flex;

          flex-direction: column;

          align-items: center;

          gap: 6px;

          margin-top: 23px;

          text-align: center;

          color: #49627f;

          font-size: 11px;
        }

        .page-footer strong {
          color: #294564;

          font-size: 12px;
        }

        .page-footer span {
          color: #7890aa;
        }

        @media (max-width: 900px) {

          .header-right {
            gap: 8px;
          }

          .secure-badge {
            display: none;
          }

          .registration-container {
            width: 94%;
          }

        }

        @media (max-width: 850px) {

          .registration-header {
            padding: 0 25px;
          }

          .page-heading {
            flex-direction: column;
            align-items: flex-start;
          }

          .step-indicator {
            display: none;
          }

        }

        @media (max-width: 650px) {

          .registration-header {
            height: 68px;
            padding: 0 18px;
          }

          .brand-logo-image {
            width: 125px;
            height: 48px;
          }

          .back-button {
            padding: 8px 12px;
            font-size: 11px;
          }

          .registration-container {
            width: 94%;
            margin-top: 24px;
          }

          .page-heading h1 {
            font-size: 29px;
          }

          .page-heading p {
            font-size: 13px;
          }

          .form-grid {
            grid-template-columns: 1fr;
          }

          .field-full {
            grid-column: auto;
          }

          .form-section {
            padding: 24px 19px;
          }

          .form-footer {
            flex-direction: column;
            align-items: stretch;
            padding: 20px 19px;
          }

          .privacy-note {
            max-width: none;
          }

          .submit-button {
            width: 100%;
            min-width: 0;
          }

          .submit-error {
            margin-left: 19px;
            margin-right: 19px;
          }

          .page-footer {
            padding: 0 15px;
          }

        }

        @media (max-width: 430px) {

          .brand-logo-image {
            width: 118px;
          }

          .page-heading h1 {
            font-size: 26px;
          }

          .registration-form {
            border-radius: 17px;
          }

        }

      `}</style>

    </div>
  );
}
