const mongoose = require("mongoose");

const lhoSchema = new mongoose.Schema(
  {
    // Automatically generated by backend
    lhoId: {
      type: String,
      unique: true,
      index: true,
      required: true,
      trim: true,
      uppercase: true,
    },

    // Organization
    // NOT REQUIRED — can be empty during testing
    organizationName: {
      type: String,
      default: "",
      trim: true,
    },

    organizationType: {
      type: String,
      default: "",
      trim: true,
    },

    locality: {
      type: String,
      default: "",
      trim: true,
    },

    address: {
      type: String,
      default: "",
      trim: true,
    },

    district: {
      type: String,
      default: "",
      trim: true,
    },

    state: {
      type: String,
      default: "",
      trim: true,
    },

    pincode: {
      type: String,
      default: "",
      trim: true,
    },

    phone: {
      type: String,
      default: "",
      trim: true,
    },

    email: {
      type: String,
      default: "",
      lowercase: true,
      trim: true,
      index: true,
    },

    website: {
      type: String,
      default: "",
      trim: true,
    },

    emergencyServices: {
      type: Boolean,
      default: false,
    },

    ambulanceAvailable: {
      type: Boolean,
      default: false,
    },

    ambulanceCount: {
      type: Number,
      default: 0,
      min: 0,
    },

    // Authorized Representative
    representative: {
      name: {
        type: String,
        default: "",
        trim: true,
      },

      designation: {
        type: String,
        default: "",
        trim: true,
      },

      phone: {
        type: String,
        default: "",
        trim: true,
      },

      email: {
        type: String,
        default: "",
        lowercase: true,
        trim: true,
      },

      role: {
        type: String,
        default: "",
        trim: true,
      },

      authLetterFileName: {
        type: String,
        default: "",
      },
    },

    // Verification documents
    verification: {
      certType: {
        type: String,
        default: "",
      },

      certNumber: {
        type: String,
        default: "",
      },

      issuingAuthority: {
        type: String,
        default: "",
      },

      issueDate: {
        type: String,
        default: "",
      },

      validUntil: {
        type: String,
        default: "",
      },

      certFileName: {
        type: String,
        default: "",
      },
    },

    identityVerified: {
      type: Boolean,
      default: false,
    },

    // Authentication
    passwordHash: {
      type: String,
      default: null,
    },

    passwordCreated: {
      type: Boolean,
      default: false,
    },

    status: {
      type: String,
      enum: [
        "pending_password",
        "pending_verification",
        "verified",
        "rejected",
      ],
      default: "pending_password",
    },

    role: {
      type: String,
      enum: ["lho"],
      default: "lho",
    },
  },
  {
    timestamps: true,
  }
);


// =========================================================
// GENERATE UNIQUE LHO ID
// =========================================================

const generateLHOId = async () => {
  const LHO = mongoose.model("LHO");

  let lhoId;
  let exists = true;

  while (exists) {
    const number = Math.floor(
      100000 + Math.random() * 900000
    );

    lhoId = `LHO-${number}`;

    exists = await LHO.exists({
      lhoId,
    });
  }

  return lhoId;
};


// =========================================================
// AUTOMATICALLY GENERATE ID BEFORE VALIDATION
// =========================================================

lhoSchema.pre("validate", async function () {
  if (!this.lhoId) {
    this.lhoId = await generateLHOId();
  }
});


module.exports = mongoose.model("LHO", lhoSchema);